server:
  port: 4466

spring:
  application:
    name: spring_security_with_aop

  datasource:
    url: jdbc:postgresql://localhost:5432/project?currentSchema=spring_security_with_aop
    username: postgres
    password: 2210
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true